# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown
highlighter:         rouge
# Setup
title:               Karthikeyansam
tagline:             'A collection of works and knowledge from various sources'
description:         'Pages to preserve my learning, knowledge and works'
url:                 http://karthikeyansam.github.io/works/
baseurl:             https://karthikeyansam.github.io/works
paginate:            5

# About/contact
author:
  name:              Karthikeyan
  url:               https://twitter.com/karthikeyansam
  email:             karthikeyansam@gmail.com

# Custom vars
version:             1.0.0
