# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Karthikeyansam
tagline:          'A collection of works and knowledge from various sources'
description:      'Pages to preserve my learning, knowledge and works'
url:              http://karthikeyansam.github.io/works/

author:
  name:           'Karthikeyan Sampath'
  url:            https://twitter.com/karthikeyansam

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karthikeyansam/lanyon
