# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://karthikeyansam.github.io/works/

author:
  name:           'Karthikeyan Sampath'
  url:            https://twitter.com/karthikeyansam

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karthikeyansam/lanyon
